name: Build docker
description: Builds and push docker image

outputs:
  image_name:
    description: Image name
    value: ${{ steps.set_outputs.outputs.image_name }}
  image_tag:
    description: Image tag
    value: ${{ steps.set_outputs.outputs.new_tag }}
  image_digest:
    description: Image digest
    value: ${{ steps.set_outputs.outputs.new_digest }}

runs:
  using: composite

  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ github.token }}

    - name: Build docker and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }} , ${{ env.registry }}/${{ github.repository }}:latest

    - name: Set outputs
      id: set_outputs
      shell: bash
      run: |
        echo 'image_name=${{ env.registry }}/${{ github.repository }}' >> $GITHUB_OUTPUT 
        echo 'new_digest=${{ steps.build.outputs.digest }}'            >> $GITHUB_OUTPUT
        echo 'new_tag=${{ steps.tag_version.outputs.new_tag }}'        >> $GITHUB_OUTPUT

    - name: Add summary of build
      id: summary
      shell: bash
      run: |
        echo '### Image release info'                                     >> $GITHUB_STEP_SUMMARY
        echo '- Image name: ${{ env.registry }}/${{ github.repository }}' >> $GITHUB_STEP_SUMMARY 
        echo '- Digest: ${{ steps.build.outputs.digest }}'                >> $GITHUB_STEP_SUMMARY
        echo '- Tag: ${{ steps.tag_version.outputs.new_tag }}'            >> $GITHUB_STEP_SUMMARY
