name: Build Docker for branches
description: Builds and push docker image for a specific branch

inputs:
  image_tag:
    description: The tag of the image, usually the branch name
    required: true

outputs:
  image_name:
    description: Image name
    value: ${{ steps.set_outputs.outputs.image_name }}
  image_digest:
    description: Image digest
    value: ${{ steps.set_outputs.outputs.new_digest }}

runs:
  using: composite

  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build docker and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.registry }}/${{ github.repository }}:${{ inputs.image_tag }}

    - name: Set outputs
      id: set_outputs
      shell: bash
      run: |
        echo 'image_name=${{ env.registry }}/${{ github.repository }}'  >> $GITHUB_OUTPUT 
        echo 'new_digest=${{ steps.build.outputs.digest }}'             >> $GITHUB_OUTPUT

    - name: Add summary of build
      id: summary
      shell: bash
      run: |
        echo '### Image release info'                                     >> $GITHUB_STEP_SUMMARY
        echo '- Image name: ${{ env.registry }}/${{ github.repository }}' >> $GITHUB_STEP_SUMMARY 
        echo '- Digest: ${{ steps.build.outputs.digest }}'                >> $GITHUB_STEP_SUMMARY
