creation_rules:
  - path_regex: \.risc\.yaml$
    shamir_threshold: 2
    key_groups:
      # Team-gruppe
      - gcp_kms:
          # Bygning-teamet
          - resource_id: 'projects/matrikkelbygning-dev-2d2c/locations/europe-north1/keyRings/ROS/cryptoKeys/matrikkel-bygning-egenregistrering-ros'
        age:
          # Sikkerhetsteamet
          - age145s860ux96jvx6d7nwvzar588qjmgv5p47sp6nmmt2jnmhqh4scqcuk0mg
      # Plattform-gruppe
      - age:
          # Plugin-backend
          - age18e0t6ve0vdxqzzjt7rxf0r6vzc37fhs5cad2qz40r02c3spzgvvq8uxz23
          # Sikkerhetsplattform
          - age1kjpgclkjev08aa8l2uy277gn0cngrkrkazt240405ezqywkm5axqt3d3tq
      # Utviklere (lokalt)
      - age:
        # Security Champions
