name: Build and Test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build, test and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run build and integration tests
        run: ./gradlew build integrationTest
      - name: Build and push docker
        uses: ./.github/actions/build-push-docker

  run-pharos:
    needs: [ build ]
    name: Run Pharos
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && github.ref_name == 'main'
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@v0.2.1
        with:
          image_url: ${{ needs.build.outputs.image_name }}@${{ needs.build.outputs.new_digest }}
