name: Dependency Submission og Dependency Review for PR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        env:
          KV_PACKAGES_PAT: ${{ secrets.KV_PACKAGES_PAT }}
      - name: Dependency review
        uses: actions/dependency-review-action@v4.5.0
        if: github.event_name == 'pull_request'
        with:
          comment-summary-in-pr: true
          deny-licenses: "AGPL-1.0-only, AGPL-1.0-or-later, AGPL-3.0, AGPL-3.0-or-later"
