name: Promote Version in Dev to Test
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Bump Version
    uses: kartverket/bygning-github-workflows/.github/workflows/promote-app.yaml@main
    permissions:
      id-token: write
    with:
      application_name: bygning-backend
      namespace_from: matrikkelbygning-dev
      namespace_to: matrikkelbygning-test
      cluster_from: atkv3-dev
      cluster_to: atkv3-dev
